rootProject.name = 'apoc'

include("extended")

//apply from: 'apoc/settings-parent.gradle'

include ':core', ':common', ':processor', ':test-utils'
project(':core').projectDir = new File(rootDir, 'apoc/core')
project(':common').projectDir = new File(rootDir, 'apoc/common')
project(':processor').projectDir = new File(rootDir, 'apoc/processor')
project(':test-utils').projectDir = new File(rootDir, 'apoc/test-utils')
////includeBuild ':apoc'
////include ':core'
//include ':processor'
//include ':common'
//include ':test-utils'
////project(':core').projectDir = new File('/Users/GiuseppeVillani/Documents/apocCore/apoc/core')
//////project(':apoc').projectDir = new File('/Users/GiuseppeVillani/Documents/apocCore/apoc')
////project(':common').projectDir = new File('/Users/GiuseppeVillani/Documents/apocCore/apoc/common')