We can extract the metadata and h2 heading from the https://en.wikipedia.org/[Wikipedia home page^], by running the following query:

[source,cypher]
----
CALL apoc.load.html("https://en.wikipedia.org/",{metadata:"meta", h2:"h2"});
----

.Results
[opts="header",cols="1"]
|===
| Output
a|
[source,json]
----
{
   "metadata":[
      {
         "tagName":"meta",
         "attributes":{
            "charset":"UTF-8"
         }
      },
      {
         "tagName":"meta",
         "attributes":{
            "name":"ResourceLoaderDynamicStyles"
         }
      },
      {
         "tagName":"meta",
         "attributes":{
            "name":"generator",
            "content":"MediaWiki 1.36.0-wmf.16"
         }
      },
      {
         "tagName":"meta",
         "attributes":{
            "name":"referrer",
            "content":"origin"
         }
      },
      {
         "tagName":"meta",
         "attributes":{
            "name":"referrer",
            "content":"origin-when-crossorigin"
         }
      },
      {
         "tagName":"meta",
         "attributes":{
            "name":"referrer",
            "content":"origin-when-cross-origin"
         }
      },
      {
         "tagName":"meta",
         "attributes":{
            "property":"og:image",
            "content":"https://upload.wikimedia.org/wikipedia/commons/1/1c/Orion_pulse_unit_%28transparent%29.png"
         }
      }
   ],
   "h2":[
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-tfa-h2"
         },
         "text":"From today's featured article",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-dyk-h2"
         },
         "text":"Did you know ...",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-itn-h2"
         },
         "text":"In the news",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-otd-h2"
         },
         "text":"On this day",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-tfl-h2"
         },
         "text":"From today's featured list",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-tfp-h2"
         },
         "text":"Today's featured picture",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-other"
         },
         "text":"Other areas of Wikipedia",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-sister"
         },
         "text":"Wikipedia's sister projects",
         "tagName":"h2"
      },
      {
         "attributes":{
            "class":"mp-h2",
            "id":"mp-lang"
         },
         "text":"Wikipedia languages",
         "tagName":"h2"
      },
      {
         "tagName":"h2",
         "text":"Navigation menu"
      }
   ]
}
----
|===

Let's suppose we have a `test.html` file like this:
[source,html]
----
<!DOCTYPE html>
<html class="client-nojs" lang="en" dir="ltr">
  <h6 i d="error">test</h6>
  <h6 id="correct">test</h6>
</html>
----

We can handle the parse error caused by `i d` through `failSilently` configuration.
So, we can execute:

[source,cypher]
----
CALL apoc.load.html("test.html",{h6:"h6"});
----
.Results
[opts="header"]
|===
| Failed to invoke procedure `apoc.load.html`: Caused by: java.lang.RuntimeException: Error during parsing element: <h6 i d="error">test</h6>
|===

or with failSilently `WITH_LIST`:

[source,cypher]
----
CALL apoc.load.html("test.html",{h6:"h6"}, {failSilently: 'WITH_LIST'});
----

.Results
[opts="header"]
|===
| Output
a|
[source,json]
----
{
  "errorList": [
    "<h6 i d="error">test</h6>"
  ],
  "h6": [
    {
      "attributes": {
        "id": "correct"
      },
      "text": "test",
      "tagName": "h6"
    }
  ]
}
----
|===

or with failSilently `WITH_LOG` (note that will be created a `log.warn("Error during parsing element: <h6 i d="error">test</h6>")` ):

[source,cypher]
----
CALL apoc.load.html("test.html",{h6:"h6"}, {failSilently: 'WITH_LOG'});
----

.Results
[opts="header"]
|===
| Output
a|
[source,json]
----
{
  "h6": [
    {
      "attributes": {
        "id": "correct"
      },
      "text": "test",
      "tagName": "h6"
    }
  ]
}
----

We can also pass an HTML string as 1st parameter, for example:
[source,cypher]
----
CALL apoc.load.html("<!DOCTYPE html> <html> <body> <p class='firstClass'>My first paragraph.</p> </body> </html>",{metadata:"meta", h2:"h2"});
----

Moreover, we can use special function for selector, putting a `()` after that and, if the function require some parameters, inserting them in a list togheter with the function.
For example, if we want to emulate a js function `getElementById(id)`, we can do:

[source,cypher]
----
CALL apoc.load.html($url, {nameKey: ['getElementById()', 'idName']})
----

.Results
[opts="header"]
|===
| Output
a|
[source,json]
----
{
  "h6": [
    {
      "attributes": {
        "id": "idName"
      },
      "text": "test",
      "tagName": "h6"
    }
  ]
}
----

Or, we can get a plain text of the whole document:

[source,cypher]
----
CALL apoc.load.html($url, {nameKey: 'getPlainText()'})
----

or of some elements, with a selector:
[source,cypher]
----
CALL apoc.load.html($url, {nameKey: ['getPlainText()', 'div']})
----

The possible functions are:
- getLinks() - Get link elements from an url
- getMediaLinks() - Get media link elements
- getPlainText(optionalSelector) - Get plain text version of a given page

plus all the function provided by https://jsoup.org/apidocs/org/jsoup/nodes/Element.html(`org.jsoup.nodes.Element`) which return a `Element` or an `Elements`, that is:

- getElementById(id) - Find an element by ID, including or under this element.
- getElementsByTag(tag) - Finds elements, including and recursively under this element, with the specified tag name.
- getElementsByClass(className) - Find elements that have this class, including or under this element.
- getElementsByAttribute(key) - Find elements that have a named attribute set.
- getElementsByAttributeStarting(keyPrefix) - Find elements that have an attribute name starting with the supplied prefix. Use data- to find elements that have HTML5 datasets.
- getElementsByAttributeValue(key,value) - Find elements that have an attribute with the specific value.
- getElementsByAttributeValueContaining(key,match) - Find elements that have attributes whose value contains the match string.
- getElementsByAttributeValueEnding(key,valueSuffix) - Find elements that have attributes that end with the value suffix.
- getElementsByAttributeValueMatching(key,regex) - Find elements that have attributes whose values match the supplied regular expression.
- getElementsByAttributeValueNot(key,value) - Find elements that either do not have this attribute, or have it with a different value.
- getElementsByAttributeValueStarting(key,valuePrefix) - Find elements that have attributes that start with the value prefix.
- getElementsByIndexEquals(index) - Find elements whose sibling index is equal to the supplied index.
- getElementsByIndexGreaterThan(index) - Find elements whose sibling index is greater than the supplied index.
- getElementsByIndexLessThan(index) - Find elements whose sibling index is less than the supplied index.
- getElementsContainingOwnText(searchText) - Find elements that directly contain the specified string.
- getElementsContainingText(searchText) - Find elements that contain the specified string.
- getElementsMatchingOwnText(regex) - Find elements whose text matches the supplied regular expression.
- getElementsMatchingText(pattern) - Find elements whose text matches the supplied regular expression.
- getAllElements() - Find all elements under document (including self, and children of children).

|===