////
This file is generated by DocsTest, so don't change it!
////

= apoc.periodic.iterate.stream
:description: This section contains reference documentation for the apoc.periodic.iterate.stream procedure.

label:procedure[] label:apoc-core[]

[.emphasis]
apoc.periodic.iterate.stream('statement returning items', 'statement per item', $config) - Same as the apoc.periodic.iterate, but returns a result for each batch (with the `batchNo` field indicating the batch number instead of `batches` field)

== Signature

[source]
----
apoc.periodic.iterate.stream(cypherIterate :: STRING?, cypherAction :: STRING?, config :: MAP?) :: (batchNo :: INTEGER?, total :: INTEGER?, timeTaken :: INTEGER?, committedOperations :: INTEGER?, failedOperations :: INTEGER?, failedBatches :: INTEGER?, retries :: INTEGER?, errorMessages :: MAP?, batch :: MAP?, operations :: MAP?, wasTerminated :: BOOLEAN?, failedParams :: MAP?, updateStatistics :: MAP?)
----

== Input parameters
[.procedures, opts=header]
|===
| Name | Type | Default 
|cypherIterate|STRING?|null
|cypherAction|STRING?|null
|config|MAP?|null
|===

== Output parameters
[.procedures, opts=header]
|===
| Name | Type 
|batchNo|INTEGER?
|total|INTEGER?
|timeTaken|INTEGER?
|committedOperations|INTEGER?
|failedOperations|INTEGER?
|failedBatches|INTEGER?
|retries|INTEGER?
|errorMessages|MAP?
|batch|MAP?
|operations|MAP?
|wasTerminated|BOOLEAN?
|failedParams|MAP?
|updateStatistics|MAP?
|===

[[usage-apoc.periodic.iterate.stream]]
== Usage Examples
include::partial$usage/apoc.periodic.iterate.stream.adoc[]

